//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("Magirenko Technologies")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Release")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("©Magirenko Technologies 2024")]
[assembly: System.Reflection.AssemblyDescriptionAttribute("Reproductor de Musica para Windows.")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("0.4.3.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("0.4.3")]
[assembly: System.Reflection.AssemblyProductAttribute("Magirenko Music")]
[assembly: System.Reflection.AssemblyTitleAttribute("magirenko_music")]
[assembly: System.Reflection.AssemblyVersionAttribute("0.4.3.0")]
[assembly: System.Runtime.Versioning.TargetPlatformAttribute("Windows7.0")]
[assembly: System.Runtime.Versioning.SupportedOSPlatformAttribute("Windows7.0")]

// Generado por la clase WriteCodeFragment de MSBuild.

